version: '3'

services:
  order-db:
    container_name: anylistDB
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}